SEQ_LEN: 128
D_MODEL: 512
N_HEADS: 8
N_LAYERS: 6
N_ENCODERS: 6
N_DECODERS: 6
FF_HIDDEN: 2048
DROPOUT: 0.1
PAD_TOKEN: 0
VOCAB_SIZE: 30000
SEQ_LEN: 175
BATCH_SIZE: 64
TRAIN_RATIO: 0.8
NUM_EPOCHS: 100
LR: 0.0001



