D_MODEL: 256
N_HEADS: 4
N_ENCODERS: 2 # 6
N_DECODERS: 2 # 6
FF_HIDDEN: 2048
DROPOUT: 0.1
SEQ_LEN: 140
BATCH_SIZE: 512
TRAIN_RATIO: 0.8
NUM_EPOCHS: 10
LR: 0.00005
DROPOUT: 0.1
GLOBAL_ATTENTION: 1
LOCAL_ATTENTION: 3
RANDOM_ATTENTION: 5

